# Generated by Django 3.2.4 on 2021-06-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='img',
            field=models.ImageField(default='Jithu.jpg', upload_to='images'),
            preserve_default=False,
        ),
    ]
